import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "AI Agents - Arc Lab",
    template: "%s - Arc Lab",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
